FROM ubuntu:latest

# Set non-interactive to avoid timezone prompts during apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Update system and install npm/nodejs
RUN apt-get update && \
    apt-get install -y nodejs npm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
