name: Sync to GitLab

on:
  push:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Push ALL branches & tags to GitLab
        run: |
          git remote add gitlab git@gitlab.com:zeruxjs/zeruxjs.git || true
          git push --force --all gitlab
          git push --force --tags gitlab